# Generated by Django 5.2.8 on 2026-01-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='telefono',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono'),
        ),
    ]
