# Generated by Django 5.2.8 on 2026-02-02 19:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=100, verbose_name='Modelo')),
                ('fecha_fabricacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de fabricacion')),
                ('kilometros', models.PositiveIntegerField(default=0, verbose_name='Kilometros')),
                ('combustible', models.CharField(default='', max_length=100, verbose_name='Combustible')),
                ('color', models.CharField(default='', max_length=100, verbose_name='Color')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='coches/', verbose_name='Imagen')),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(default='', max_length=100, verbose_name='Apellidos')),
                ('puesto', models.CharField(default='', max_length=100, verbose_name='Puesto')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='Fecha de contratacion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='coches/galeria/', verbose_name='Imagen Adicional')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='app_agencia_coches.cars')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agencia_coches.employee', verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cars',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='coches', to='app_agencia_coches.extra', verbose_name='Extras'),
        ),
    ]
